# Generated by Django 4.0.1 on 2022-03-25 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppt_submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='t',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ppt_submission.topic'),
        ),
    ]
