# Generated by Django 4.0.3 on 2022-03-26 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppt_submission', '0003_alter_student_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='tt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ppt_submission.student'),
        ),
    ]
