# Generated by Django 4.0.3 on 2022-03-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt_submission', '0007_remove_file_student_file_id_file_tt_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='roll_check',
            field=models.IntegerField(default=10, max_length=10),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
