# Generated by Django 4.0.3 on 2022-03-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt_submission', '0011_alter_file_roll_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(error_messages={'unique': 'you have already selected a topic!'}),
        ),
    ]
