# Generated by Django 4.0.1 on 2022-04-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppt_submission', '0013_alter_topic_topic_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='t',
            new_name='topic',
        ),
    ]
