# Generated by Django 4.0.1 on 2022-04-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppt_submission', '0015_alter_file_tt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='tt',
            new_name='student',
        ),
    ]
